### ISSUE TITLE
Some method should fix it and some var should add in .h

### ISSUE THREAD

**Issue by lu5914018** [dopcn/DOPDropDownMenu#11]
Thank you for your project which you coding , it help me to learn how to complete my works.
But I found someting it should be fix.
1.add more color var in .h to use.
2.something wrong in here ,when i used:

if (cell.textLabel.text == [(CATextLayer *)[_titles objectAtIndex:_currentSelectedMenudIndex] string]) {
        cell.backgroundColor = [UIColor colorWithWhite:0.9 alpha:1.0];
    }

it is in method:
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath

and then i fix it:
if ([cell.textLabel.text isEqualToString:[(CATextLayer *)[_titles objectAtIndex:_currentSelectedMenudIndex] string]]) {
        cell.backgroundColor = [UIColor colorWithWhite:0.9 alpha:1.0];
    }

**Comment by dopcn** [comment]
Yes you are right will fix it

**Comment by dopcn** [comment]
fixed
