### ISSUE TITLE
sub menu and maybe multi selection?

### ISSUE THREAD

**Issue by dopcn** [dopcn/DOPDropDownMenu#6]

**Comment by orchidFang** [comment]
![img_0213](https://cloud.githubusercontent.com/assets/6478487/6141046/043b45ee-b1db-11e4-94c6-4b638f5dcab2.PNG)

当点击过 DropDownMenu后，再点击+push到另一个TableViewcontroller后，再返回时会出现TableView下移的bug

**Comment by dopcn** [comment]
@orchidFang 哈直接看源码问题出在哪吧，不多
