### ISSUE TITLE
push 后，pop回来 的bug

### ISSUE THREAD

**Issue by orchidFang** [dopcn/DOPDropDownMenu#7]
当点击过 DropDownMenu后，再点击+push到另一个TableViewcontroller后，再返回时会出现TableView下移的bug
![img_0213](https://cloud.githubusercontent.com/assets/6478487/6141079/81e6fb0a-b1db-11e4-9179-a2e3aa2e153c.PNG)

**Comment by dopcn** [comment]
@orchidFang 可以先在 viewwilldisappear 的时候让下拉菜单消失

**Comment by scuxiayiqian** [comment]
@dopcn 具体怎么写才能解决这个bug？

**Comment by dopcn** [comment]
@scuxiayiqian 最好用 objc 写

**Comment by dopcn** [comment]
@orchidFang @scuxiayiqian 添加了dismiss方法，在 control 要消失的时候手动调用使menu消失
